<a href="https://colab.research.google.com/github/ABHIRAJAWAT-07/AbhiRajawat-07/blob/main/NUMPY_PY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
b=np.array([1,2,3,4])
print(b)

[1 2 3 4]


In [ ]:
np.array([1,2,3,4], dtype=float)

array([1., 2., 3., 4.])

In [ ]:
#np arange
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
#with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
#np.ones
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.random.random((3,2))

array([[0.64129984, 0.21073802],
       [0.29290954, 0.36395207],
       [0.96252776, 0.44711953]])

In [ ]:
np.linspace(-5,5,5)

array([-5. , -2.5,  0. ,  2.5,  5. ])

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#ARRAY ATTRIBUTES

#NDIM----NO. OF DIMENSION
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)



In [ ]:
a3.ndim

3

In [ ]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [ ]:
a1*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18], dtype=int32)

In [ ]:
a1**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [ ]:
a1= np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[46., 62., 74.],
       [54., 30., 56.],
       [13., 96., 58.]])

In [ ]:
np.sum(a1)

np.float64(489.0)

In [ ]:
np.mean(a1,axis=1)

array([60.66666667, 46.66666667, 55.66666667])

In [ ]:
np.sin(a2)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [ ]:
np.tan(a1)

array([[-2.08661353, -1.09750978, -5.73702254],
       [ 0.6738001 , -6.4053312 , -0.61127369],
       [ 0.46302113, -5.45134011,  8.33085685]])

In [ ]:
#index slicing
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1,2]

np.int64(6)

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[0,1,0]

np.int64(2)

In [ ]:
a3[0,0,0]

np.int64(0)

In [ ]:
a3[1,1,0]

np.int64(6)

In [ ]:
#slicing
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [ ]:
a1[2:6]

array([2, 3, 4, 5], dtype=int32)

In [ ]:
a1[2:6:4]

array([2], dtype=int32)

In [ ]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [ ]:
a2 = np.arange(12,dtype=int).reshape(3,4)

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1,0::3]

array([4, 7])

In [ ]:
a2[0:2,1:4]

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
a3 =np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[0,1]

array([3, 4, 5])

In [ ]:
a3[1,0:3,1]

array([10, 13, 16])

In [ ]:
a3[2,1:,1:3]

array([[22, 23],
       [25, 26]])

In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[::2,0,::2]


array([[ 0,  2],
       [18, 20]])

In [ ]:
#iterating
a2.T

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [ ]:
a2.ravel()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
#stacking
#splitting
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [ ]:
np.hstack((a2,a3))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 3 dimension(s)

In [ ]:
# fancy indexing
a=np.arange(24).reshape(6,4)

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a[:,[0,2,3,]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])